import { WeeklyReport } from "./types"

export const SAMPLE_DATA: WeeklyReport = {
  generated_at: new Date().toISOString(),
  run_date: new Date().toISOString().slice(0, 10),
  date_range: "last 7 days",
  total_clients: 3,
  needs_attention: 1,
  clients: [
    {
      domain: "blackstone.com",
      client_name: "Blackstone",
      total_emails: 12,
      total_threads: 4,
      flag: "issue",
      severity: "high",
      last_activity: new Date().toISOString().slice(0, 10),
      issue_count: 1,
      fyi_count: 2,
      routine_count: 1,
      issues: [
        {
          thread_id: "t1",
          subject: "Q2 fund admin fee reconciliation mismatch",
          flag: "issue",
          severity: "high",
          summary: "Client is raising a $45k discrepancy in Q2 fee calculations and is asking for a same-week response. This has escalated to the CFO.",
          action_required: "Prepare fee reconciliation summary and schedule call with Blackstone CFO by Friday.",
          participants: ["cfo@blackstone.com", "ops@blackstone.com"],
          date_range: "2025-04-20 to 2025-04-23",
          email_count: 6,
        },
      ],
      fyi: [
        {
          thread_id: "t2",
          subject: "New fund launch — capital call schedule",
          flag: "fyi",
          severity: "medium",
          summary: "Blackstone launching a new $2B fund; requesting our support on the capital call schedule.",
          action_required: "Review capital call schedule template.",
          participants: ["pm@blackstone.com"],
          date_range: "2025-04-22",
          email_count: 3,
        },
        {
          thread_id: "t3",
          subject: "Audit coordination for Q1 close",
          flag: "fyi",
          severity: "low",
          summary: "Standard audit coordination touchpoint for Q1 close, nothing unusual.",
          action_required: null,
          participants: ["audit@blackstone.com"],
          date_range: "2025-04-21",
          email_count: 2,
        },
      ],
      routine: [
        {
          thread_id: "t4",
          subject: "Weekly call scheduling",
          flag: "routine",
          severity: "low",
          summary: "Scheduling logistics for the standing weekly call.",
          action_required: null,
          participants: ["ea@blackstone.com"],
          date_range: "2025-04-19",
          email_count: 1,
        },
      ],
    },
    {
      domain: "kkr.com",
      client_name: "KKR",
      total_emails: 5,
      total_threads: 2,
      flag: "fyi",
      severity: "low",
      last_activity: new Date().toISOString().slice(0, 10),
      issue_count: 0,
      fyi_count: 1,
      routine_count: 1,
      issues: [],
      fyi: [
        {
          thread_id: "t5",
          subject: "NAV statement question",
          flag: "fyi",
          severity: "low",
          summary: "KKR requesting clarification on the treatment of a specific line item in the April NAV statement.",
          action_required: "Send written explanation of NAV calculation.",
          participants: ["ops@kkr.com"],
          date_range: "2025-04-22",
          email_count: 3,
        },
      ],
      routine: [
        {
          thread_id: "t6",
          subject: "Monthly reporting package delivered",
          flag: "routine",
          severity: "low",
          summary: "Confirmation that the April reporting package was received.",
          action_required: null,
          participants: ["finance@kkr.com"],
          date_range: "2025-04-20",
          email_count: 2,
        },
      ],
    },
    {
      domain: "apollo.com",
      client_name: "Apollo Global Management",
      total_emails: 3,
      total_threads: 1,
      flag: "routine",
      severity: "low",
      last_activity: new Date().toISOString().slice(0, 10),
      issue_count: 0,
      fyi_count: 0,
      routine_count: 1,
      issues: [],
      fyi: [],
      routine: [
        {
          thread_id: "t7",
          subject: "Quarterly investor letter draft review",
          flag: "routine",
          severity: "low",
          summary: "Routine round of feedback on the quarterly investor letter draft.",
          action_required: null,
          participants: ["ir@apollo.com"],
          date_range: "2025-04-18",
          email_count: 3,
        },
      ],
    },
  ],
}
